### ISSUE TITLE
[BUG]Exporter will not work in machines without Go installed

### ISSUE THREAD

**Issue by vipinvkmenon** [SAP/terraform-exporter-btp#185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform exporter are you using?

0.1.0-beta

### What version of the Terraform CLI are you using?

1.8.0

### What type of issue are you facing

bug report

### Describe the bug

On Systems that do not have `go` installed, the CLI will exit with error as it will not be able to execute the `go mod` command:

```
🚀 Creation of resource list started ...

⣾  collecting resources
2024/11/18 19:15:08 read doc failed for data-sources, btp_subaccount: could not find docs for data-sources btp_subaccount
```
As this error is not handled the propagated error is the read doc failed error.

### Expected Behavior

The binary ideally should not need go installed as a prerequisite.

**Comment by lechnerc77** [comment]
Isn't this the same error that was reported here: #182 ?

**Comment by vipinvkmenon** [comment]
While the error is the same, the main reason for creating this bug was to discuss an alternative approach to the current `go mod download` method to acquire the documents makes sense, as this reduces the dependency of the user having to have go installed on their system. (Of course, we can always keep go installation as a dependency). 

As a side note, the error here is the same as in #182 as the error as go run [error](https://github.com/SAP/terraform-exporter-btp/blob/b93982c89fafc095ce3cad33f3822fec5938f3fd/pkg/tfutils/tfDocs.go#L71) is not [propagated](https://github.com/SAP/terraform-exporter-btp/blob/b93982c89fafc095ce3cad33f3822fec5938f3fd/pkg/tfutils/tfDocs.go#L127) as of now and should be fixed as well.
