### ISSUE TITLE
[BUG] asks for confirmation of overwriting directory twice under some conditions

### ISSUE THREAD

**Issue by nikolockenvitz** [SAP/terraform-exporter-btp#206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform exporter are you using?

0.1.0-beta2

### What version of the Terraform CLI are you using?

1.10.2

### What type of issue are you facing

bug report

### Describe the bug

When I run the export command for the first time, it obviously doesn't ask for confirmation to overwrite any existing directory. When I run it again (after it completed on its own, with errors, before), I am asked for confirmation. Good until here. If I now stop the export command (Ctrl+C) and run it again afterwards, I am asked twice.

```
C:\Users\...>btptf_0.1.0-beta2_windows_amd64.exe export --subaccount 5...4 --verbose
...
```

```
C:\Users\...>btptf_0.1.0-beta2_windows_amd64.exe export --subaccount 5...4 --verbose

🚀 Terraform configuration export started ...

set up config directory "generated_configurations_5...4"
temp file created at C:\Users\...\AppData\Local\Temp\provider.tf1750713480\provider.tf
the configuration directory already exist. Do you want to continue? If yes then the directory will be overwritten (y/N): y
existing files will be overwritten

^C
```

```
C:\Users\...>btptf_0.1.0-beta2_windows_amd64.exe export --subaccount 5...4 --verbose

🚀 Terraform configuration export started ...

set up config directory "generated_configurations_5...4"
temp file created at C:\Users\...\AppData\Local\Temp\provider.tf2079069610\provider.tf
the configuration directory already exist. Do you want to continue? If yes then the directory will be overwritten (y/N): y
existing files will be overwritten
the configuration directory already exist. Do you want to continue? If yes then the directory will be overwritten (y/N): y
existing files will be overwritten
```

### Expected Behavior

Maybe there's a good explanation for this, but generally I would expect it to only ask once in all cases.

### Steps To Reproduce

see above

### Additional context

Windows/cmd

**Comment by lechnerc77** [comment]
Analysis result: In case the process was aborted more than one configuration directory is left. 
In this scenario restarting the CLI needs to overwrite two directories and hence prompts the user twice. 

The prompt does not qualify the directory to be overwritten which is confusing. 

Fix will be provided adding the directory to be re-created to the output.
